### PR TITLE
ProtoBuf 1.0.0

### LINKED ISSUE #201: Open to package overhaul?
At RelationalAI, @Drvi and I have undertaken doing a native-julia protoc implementation (called `protojl`). It parses proto files and can generate the appropriate modules/structs/serialize/deserialize for full protobuf integration. It solves some of the long-standing issues people have had with protobuf in Julia: weight of the protoc binary dependency on runtime applications, performance/allocations of serialize/deserialize, and improves coverage over the entire protobuf format specification.

We've started using it internally at RAI, but our goal since the beginning was to contribute back to the community, so robustness of the code can be accelerated and everyone can benefit. In lieu of starting a 2nd package, we'd rather just overhaul this existing package, as long as current maintainers agree. We're happy to assume maintainership of the new code going forward and are eager to support other applications/industry use.

If there are major concerns, let's discuss here; we're planing on putting up a PR sometime next week.

cc: @tanmaykm @aviks

### PR DESCRIPTION
**Pull request by Drvi**
closes #201

As mentioned in #201, this is a complete rewrite of the package, it does not quite reach feature parity with the current master, most noticeably we currently lack the ability to generate code for `Service`s and `RPC`s, we do hope to fix that in the near future. The version bump to 1.0.0 is certainly to signal a breaking change and not maturity:)

Since this is a complete rewrite from scratch and we'll be happy to take over the maintenance of this package once this is merged, I've updated the `LICENSE.md` file accordingly, please let me know if you are agree with the proposed changes.

A believe this this change should fix some of the open issues:
* #200 (well, this is only partially solved since we don't support services which the user probably needs)
* #181 (our parser does accept optional fields in proto3, it just doesn't do anything interesting with them)
* #179 (I've noticed cca 10x speedup in the provided benchmarking code)
* #137 (from my experiments with googleapis, this seemed to work fine)
* #98 (we generate a tree of directories that copies the proto package structure, I believe this should help with filename collisions)

cc: @quinnj

### CODE REVIEW

**Review by quinnj — APPROVED** [review]
Thanks @Drvi! This looks great!

**Comment by Drvi** [comment]
Thanks, @quinnj! @tanmaykm, are you also ok with this merge?

**Comment by tanmaykm** [comment]
Thanks @Drvi and @quinnj! Sure, let's merge this.

**Comment by Drvi** [comment]
I don't yet have the permissions necessary to merge PRs so, please, could you do the honors, @tanmaykm?:) And if possible, make me the owner of this repo, I need to set up Documenter secrets.

**Comment by quinnj** [comment]
I've added you as an admin @Drvi; merge away!

**Pull request merged**
