### PR TITLE
Julia 0.6 compatability

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Comment by malmaud** [comment]
Is it important that this keeps support for Julia 0.4?

**Comment by malmaud** [comment]
@tanmaykm ?

**Comment by tanmaykm** [comment]
I think it is okay to drop 0.4 support at this point.

**Comment by malmaud** [comment]
Should be g2g now.

**Comment by tanmaykm** [comment]
Thanks. LGTM. We can merge and maybe do a separate PR to better coverage.

**Pull request merged**
