### PR TITLE
use Compat to export hasproperty cleanly

### LINKED ISSUE #154: [BUG] isdefined(::ProtoType, ::Symbol) not working on some readproto types
Still trying to update TensorBoardLogger.

It seems that sometimes a field returns false to `isdefined` even if it is actually defined, and I can access it.

```julia
julia> isdefined(ev[3], :summary)
false

julia> typeof(ev[3].summary)
TensorBoardLogger.tensorboard.Summary
``` 

The proto file in question is [this](https://github.com/PhilipVinc/TensorBoardLogger.jl/blob/master/proto/event.proto) and the code generated is [here](https://github.com/PhilipVinc/TensorBoardLogger.jl/blob/threadsafe/src/protojl/tensorboard/event_pb.jl)

### PR DESCRIPTION
**Pull request by tanmaykm**
This adds dependency on Compat to export `hasproperty` cleanly for Julia versions < 1.2.
Also bumps minor version because of dependency addition.

fixes #154

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Thanks a lot for this!

However, I don't think you should bump. Semver specifies you should bump minor versions when there are API breakages, and is an implicit information about the API you provide to other developers/users.

Addition/removal of dependencies is unrelated, and addressed by the Pkg resolver accordingly.

I would bump only to 0.9.2

**Comment by tanmaykm** [comment]
Hmm... I am not sure about that... I think we should update the minor version since we have added a new dependency.

**Comment by PhilipVinc** [comment]
I still stand by my interpretation of semver, but then, since it's 0.x It's not really well defined anyway... so go ahead!

If/when you tag a new release with this, I should be able to tag a new release of TensorBoardLogger

**Comment by tanmaykm** [comment]
:+1: merging now

**Pull request merged**
