### PR TITLE
update codegen to handle import issues

### PR DESCRIPTION
**Pull request by tanmaykm**
Update codegen to have import in generated code work on both Julia 0.6 and 0.7

fixes: #110 
related: #109, #106

### CODE REVIEW

**Comment by tanmaykm** [comment]
Will merge this in a bit, as all tests pass and there are further updates dependent on this.

**Comment by zhouyan** [comment]
I am still having issues with PR. It does not seem to be fatal error, but it produce warnings. For example, say the ProtoBuf package has a nested structure, which leads to the master module file being generated as

```
module A
module B
include("AB_pb.jl")
end
end
```
and another project that using ProtoBuf has dependency on `A.B`, and itself generate a ProtoBuf Julia module, but it has a submodule also named `B`
```
module C
module B
include("CB_pb.jl")
end
end
```
Now within in `CB_pb.jl` the following is generated,
```
import A
import A.B
```
And it leads to identifier conflicts.

It seems to be harmless warnings but still quite annoying. The reason for different projects having the same submodule is as in the following scenario:

We have multiple projects, say with names saved `proj1`, `proj2`. And under each project the protobuf modules are all under `proj1.proto`, `proj2.proto` etc. This way, we are sure that human written code are under namespace `proj1` etc., while generated code are under another namespace, and thus there shall never be any conflicts.

**Comment by tanmaykm** [comment]
Could you post some proto files to simulate this at my end?

**Comment by tanmaykm** [comment]
I suppose it is something like:
```
julia> module A
           module B
               import A
               import A.B
               const name = "A.B"
           end
       end
A

julia> module C
           module B
               import A
               import A.B
               import C
               import C.B
               const name = "C.B"
           end
       end
WARNING: import of A.B into B conflicts with an existing identifier; ignored.
C
```

Then it is harmless as you indicated, because:
```
julia> C.B.A.B == C.B
false

julia> C.B.A.B.name
"A.B"

julia> C.B.name
"C.B"
```

And the generated code uses full type names everywhere.

**Comment by tanmaykm** [comment]
I think the warning can be avoided by reversing the hierarchy. That is by having `proto.proj1` and `proto.proj2` instead, if that is possible.

**Comment by zhouyan** [comment]
See my comment above. It is exactly the solution I come up with. The only issue is that we use protobuf for GRPC service, which involves half a dozen languages in our system and that's going to be a very destructive change. So compared to that, I think some harmless warning is more acceptable, especially considering that it only happens in precompiling stage, and thus only seen by Julia developers (namely me in our team). We use docker for deployment, and all pre-compile cache is generated during build phase of docker images, and thus normal user does not see it.

**Comment by zhouyan** [comment]
Actually that's not even a viable solution even if we only have Julia to consider. Julia module cannot be "re-opened" like C++ nanmespace or python namespace modules or ruby. So with a top-level `proto` module exist, the second project is going to get a conflict if it is ever used with the first project together.

**Comment by tanmaykm** [comment]
Okay. I have been also thinking more in the lines of only importing top level module. That is, `import A` and use fully qualified names everywhere. The issue with #110 was that fully qualified names were not used everywhere in the generated code. But I think that is fixable.

I shall put that up as a different PR.

**Comment by tanmaykm** [comment]
Actually I could do that in this PR itself as it already has all the changes to use fully qualified names.

@zhouyan could you give this a try?

**Comment by zhouyan** [comment]
Won’t be able to do it now. Will do first thing in the morning

**Comment by tanmaykm** [comment]
Merging and moving on to further changes.

**Comment by zhouyan** [comment]
sorry for the late reply. With the latest patch, I am again getting the `Main` issue as `_ProtoBuf_Top_` resolves to `Main`.

**Comment by tanmaykm** [comment]
No worries. Yes, it would resolve to `Main` if the code is included at top scope. When included within a package, it resolves to the module corresponding to that package.

**Comment by zhouyan** [comment]
That's the error I am having now. Effectively the generated code is now,
```
module proto_mod_a
_ProtoBuf_Top_ = Main
end

module proto_mode_b_from_another_project
_ProtoBuf_Top_ = Main
import ._ProtoBuf_Top_.proto_mod_a
end
```
And again the import in the second module cannot be resolved

**Comment by tanmaykm** [comment]
The above code works for me:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.4 (2018-07-09 19:09 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> module proto_mod_a
       _ProtoBuf_Top_ = Main
       end
proto_mod_a

julia> module proto_mode_b_from_another_project
       _ProtoBuf_Top_ = Main
       import ._ProtoBuf_Top_.proto_mod_a
       end
proto_mode_b_from_another_project
```

Also, it is possible to influence (if you need it to be different) it by assigning `_ProtoBuf_Top_` in the scope where the code is included.

**Comment by zhouyan** [comment]
That's because in your case `proto_mod_a` is defined in `Main` and `Main.proto_mod_a` does exist. In my case, the two protobuf modules are in two separate files.

**Comment by tanmaykm** [comment]
Well, they can be in separate files, as long as they are finally included in the same scope:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.4 (2018-07-09 19:09 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> module MyPkg
           module proto_mod_a
               using Compat
               const _ProtoBuf_Top_ = @static isdefined(parentmodule(@__MODULE__), :_ProtoBuf_Top_) ? (parentmodule(@__MODULE__))._ProtoBuf_Top_ : parentmodule(@__MODULE__)
           end

           module proto_mode_b_from_another_project
               using Compat
               const _ProtoBuf_Top_ = @static isdefined(parentmodule(@__MODULE__), :_ProtoBuf_Top_) ? (parentmodule(@__MODULE__))._ProtoBuf_Top_ : parentmodule(@__MODULE__)
               import ._ProtoBuf_Top_.proto_mod_a
           end
       end
MyPkg
```

**Comment by zhouyan** [comment]
Here's MWE,

First module
```
$ cat proto_a/src/proto_a.jl 
module proto_a
const foo = 1
end
```

Second module
```
$ cat proto_b/src/proto_b.jl
module proto_b
using Compat
const _ProtoBuf_Top_ = @static isdefined(parentmodule(@__MODULE__), :_ProtoBuf_Top_) ? (parentmodule(@__MODULE__))._ProtoBuf_Top_ : parentmodule(@__MODULE__)
import ._ProtoBuf_Top_.proto_a
const foo = prot_a.foo
end
```

Both directory `proto_a` and `proto_b` are in `$HOME/.julia/v0.6`, so Julia default package lookup will  find them,

now
```
julia> using proto_b
WARNING: could not import Main.proto_a into proto_b
ERROR: LoadError: UndefVarError: prot_a not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] eval(::Module, ::Any) at ./boot.jl:235
 [3] _require(::Symbol) at ./loading.jl:490
 [4] require(::Symbol) at ./loading.jl:405
while loading /Users/Zhou/.julia/v0.6/proto_b/src/proto_b.jl, in expression starting on line 5
```

**Comment by zhouyan** [comment]
That's the problem, they come from different projects. The first project is a common dependency of others. Its module need to be able to be used independently of others. So it cannot be included in the same module with other.

**Comment by tanmaykm** [comment]
Looks like there's a typo: shouldn't it be `proto_a` instead of `prot_a`?

**Comment by zhouyan** [comment]
Yeah, it's a typo, but the error will be the same, the root issue is that `proto_a` cannot be imported to `proto_b` this way

**Comment by tanmaykm** [comment]
It works for me:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.4 (2018-07-09 19:09 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using proto_a

julia> using proto_b
```

You need to do `using proto_a` first.

**Comment by tanmaykm** [comment]
Yeah. Works either way:
```

julia> include("proto_a/src/proto_a.jl")
proto_a

julia> include("proto_b/src/proto_b.jl")
proto_b
```

**Comment by zhouyan** [comment]
Not using `include`, let Julia find the module through `LOAD_PATH` and not using `proto_a` first will produce the error. The key is `proto_a` has to be binded in `Main` first. If it is neither `include` nor `using` or `import` first before `using proto_b`, it generates an error

**Pull request merged**
