### PR TITLE
Fix dictionary encoding and decoding

### PR DESCRIPTION
**Pull request by JamieMair**
Fixes issues described in https://github.com/JuliaIO/ProtoBuf.jl/issues/233

Note that these would be **breaking changes** for any messages serialised which include dictionaries. Previously stored messages will fail when being deserialised. I am not 100% certain that these changes should be merged, but it is worth considering if the existing code did not match the existing specification. However, changing this may affect downstream users that are storing data which includes `Dict` types.

### CODE REVIEW

**Comment by Drvi** [comment]
Thank you @JamieMair, well spotted. This seems to indeed be a bug in ProtoBuf.jl, the current approach to encoding/decoding `maps`  might be slightly more performant but, as you point out, the spec seems to be pretty adamant that `maps` should be as similar to repeated messages of pairs as possible (even though they are not practically compatible, repeated messages can have duplicated "keys" while `maps` presumably do not.)

As comment about this being a breaking change -- I think this qualifies as a bug and should be released as a patch version. I'll check downstream users on JuliaHub and open issues if necessary, giving them some time to adjust.

Can I trouble you for writing a tests/tests for repeated messages and `map`s being interchangeable?

**Comment by JamieMair** [comment]
> the current approach to encoding/decoding `maps` might be slightly more performant

I agree, this additional overhead seems a bit redundant, but at least one can use arrays if that is an issue.

> Can I trouble you for writing a tests/tests for repeated messages and `map`s being interchangeable?

I can have a go when I next get some time to work on this. Just to check, would this involve something like
1. Create a `PairStruct` similar to `TestStruct` with a key and a value
2. Add the encoding/decoding methods 
3. Encode an array of these structs, and then check whether this is equivalent to encoding a Dict
4. Also check that the array of these structs can be decoded into a Dict?

Is there something simpler I can do, or have I missed anything?

**Comment by JamieMair** [comment]
Great! I'll get on that when I next have a little time. Thanks for the quick response!

**Comment by JamieMair** [comment]
@Drvi I have just found some time to add in the unit tests you asked for. Feel free to make any changes you want. Thanks for the support on this PR.

**Comment by Drvi** [comment]
Ah, good catch @JamieMair I think I have a fix for that.

**Comment by Drvi** [comment]
@JamieMair Can you try again?

**Comment by JamieMair** [comment]
@Drvi Yes, that's amazing. All works great on my end - I've removed our workaround. Thanks for finishing this one off!

**Pull request merged**
